### ISSUE TITLE
A lot of database files are created in the build directory

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1037]
When running a simulation test, e.g. `cothority/cosi/simulation/simul_test.go`, a lot of database files are created under the build directory. It'll be better if there is a way to automatically clean them up.

**Comment by jeffallen** [comment]
This is "by design" in that when I did the last round of work about making sure temp db's are deleted, I decided that the simulation build directory should be considered a working directory and that whatever created it should be responsible for cleaning it up, instead of considering the DB files made by simulations to be temporary DBs that should clean themselves up.

So, this issue is now about, "should the simulation driver program clean up the build directory at the end of a simulation?"

I don't know the pros/cons of that question.

**Comment by kc1212** [comment]
I confirm it is cleaned up (tried in the coin simulation), closing
