### ISSUE TITLE
syncChain does not refresh forward links

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1244]
Imainge that a node has blocks with indexes: 0 -> <- 1. It is asked to make a forward link to block 3. It calls syncChain to find block 2, and integrates it into it's DB. It now has:

 0 -> <- 1  <- 2

This issue is to fix that so that once 2 is fetched, the forward link on 1 will be also updated.

**Comment by jeffallen** [comment]
Some more/related problems:
1. the input from getBlocks must always be verified before it is used, it is untrusted data. (there is one in StoreSkipBlock, where we are making the backlinks)
2. separate calls to s.db.Store which are transactionally related (i.e. I store 2 and then store a new copy of 0 because 2 has a back link to 0 and I need to get the new forward link to 2) need to be done inside of one BoltDB transaction, so that the database is always consistent.

It looks like we need some kind of function called "verifyStoreAndUpdateForwardLinks" which encapsulates all of that into one function.

On consistent vs. complete. Linus and I think that the promise skipchain makes to local apps (i.e. verifiers for evoting) is that the blocks stored in the local DB have consistent links to each other, but that there might be holes in the chain, so that we can get the benefits of the skipchain.

But: making the rule that all backlinks of all newly discovered blocks are traversed in order to preserve consistency means we'll always fetch to completeness, because we will fetch back link 0 of each newly discovered block, marching all the way back until the last block that we have in our DB.

Still got to think about this some.

**Comment by ineiti** [comment]
I think this issue is closed with the latest changes to the skipchain:
- when creating forward links, the source- and destination-block is sent to all other nodes, so both the forward- and backward-links are updated.
- I'm not sure we need to be consistent with regard to your block 0 and block 2 example. What I did is to start by updating the forward-links of block 0, then adding block 2. This means that we can verify the forward-link to be correctly signed when adding block 0, and then verifying there is a forward-link when adding block 2.

Does that make sense?
