### ISSUE TITLE
Finish adapting java/kyber to go/kyber

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1257]
There are still some differences in naming and using of the java/kyber library and go/kyber library. Please edit this description to point out differences, so we can do them:
- no `XOF` in java
- use same arguments as in go: `point.Mul(scalar, point)` and others
- add `Point.Zero`, `Scalar.One`, `Point.Base`

**Comment by kc1212** [comment]
I was thinking how we can nicely implement the java interface while doing that java lib PR. There is one thing that I think defeats the purpose of using an interface in the current implementation. That is---we use the `Ed25519Point` constructor everywhere. It gives us back an ed25519 point so we're not directly using the point interface anymore, but the actual class methods. As a result, if we change all our `Ed25519Point` to `Point`, a lot of the code will break because there are static methods in `Ed25519Point` like `embed` that are not a part of the interface.

I propose the following, never use the constructor such as `Ed25519Point` directly. Instead, write something like `public static Point Ed25519Point.New()` for everything that implements the `Point` interface. I further propose we add a very simple `Suite` in there like kyber, it can be a simple one at first. So that we can switch groups easily in the future.

**Comment by jeffallen** [comment]
We are doing this as guided by the needs of other jobs.
