### ISSUE TITLE
Implement view-change

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1277]
After #1275 is done, we need a way for a node to step up as new leader in case he didn't get any request for more than a threshold time.

**Comment by kc1212** [comment]
My proposal:

We initialise a leader-rotation-interval `r` in terms of the number of skipchain blocks. This configuration is stored in the genesis block. Effectively, the leader of the `n`th skipblock is `n mod r`. Thus, everybody has a consistent view of the current leader. Regarding the implementation, since `updateCollection` is called _after_ a new skipblock is created, we add some logic in there to check the latest index. Depending on the index, the new leader starts to poll for transactions and the old leader stops.

**Comment by nikkolasg** [comment]
IIRC the proper way to do it by requesting everybody to continuously detect if the leader is up or not, and if a node thinks the leader is down, he broadcast a view change message designating the new leader (round robin or other more complex selection). In turn, every node receiving that message must broadcast it as well if he agrees (with his own signature of course). If more than a threshold of nodes correctly designate the same leader, then the new leader takes place.
It's more complex in the original [paper](http://pmg.csail.mit.edu/papers/osdi99.pdf) (section 4.4) but it seems to be the idea.

**Comment by kc1212** [comment]
A simple version is implemented in https://github.com/dedis/cothority/pull/1350, closing. We document ways which we can improve view-change in https://github.com/dedis/cothority/issues/1374.
