### ISSUE TITLE
Simplify Maven-build

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1408]
Look if we can have:

1. continuous build of jar-file
2. make 
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
behave nicer if gpg is not installed.

Look if https://maven.apache.org/guides/introduction/introduction-to-profiles.html helps.

**Comment by jeffallen** [comment]
@darekzbik Can you please show me the error you are having? When I modify my PATH to make sure that the gpg2 binary is not available, I am still able to run `mvn package` in order to generate the JAR file. When I use `mvn verify` in order to generate the package and then sign it, I get:

```
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ cothority ---
/bin/sh: gpg2: command not found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

So it seems to me it should be possible for the CI to make an unsigned jarfile by changin .travis to run `mvn package`.

**Comment by darekzbik** [comment]
@jeffallen you are right - something was wrong at my side. Sorry for making noise. Just close it as 'not an issue'
