### ISSUE TITLE
Further ByzCoin optimizations

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1409]
Currently, omniledger does the following in `startPolling`:

1. Ask all other nodes for new transactions
2. Calculate the next block during `blockInterval / 2` seconds
3. Send it off for verification
4. Wait for the block to be verified
5. Wait for `blockInterval` seconds

This is still very inefficient:
- point 1. should be done either in gossipping mode or independent of the block creation
- 2. & 4.: `startPolling` could assume that the block will be accepted and already start calculating the next block
- 5. this will make the actual blockinterval to be: 
`time(getTransactions) + blockInterval / 2 + time(verification) + blockInterval`
So it should make sure that the _tick_ gets in _every_ `blockInterval` instead of this formula.

This work will let us undertake another cleanup we know we need, which is that createStateChanges needs to be broken into selectTransactions and createStateChanges. selectTransactions should be able to drop transactions which are not possible to be dropped right now because of the convoluted API of createState changes. See this review conversation: https://github.com/dedis/cothority/pull/1464#discussion_r216937003
This same refactoring will allow us to correctly fix #1359.

**Comment by ineiti** [comment]
See also #1311

**Comment by kc1212** [comment]
I've been thinking about how to pipeline the transaction processing and block creation.

The rough idea is to use the pipeline approach. There will be one go-routine collecting transactions and sends the txs to a channel, this is the producer. A worker will pick up these txs from the channel and update some ephemeral statetrie to produce state changes. Finally, a consumer, who runs itself every blockinterval, will collect the new txs and state changes to create a block.

The most tricky part of this approach is that we still need to be stateful because the consumer needs the txs for the block, which is exactly what the pipeline pattern tries to avoid... Still thinking

**Comment by ineiti** [comment]
Why do you separate the worker and the consumer? As far as I can see, there is one producer, one worker, and one consumer. This looks like a good indication that you don't need to go too far into producer/consumer land and can keep it much simpler...
