### ISSUE TITLE
java: Omniledger.Proof verifications

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1440]
`Proof.verify` lacks a proper verification to know if the proof is actually valid, given a `SkipChainID`.

**Comment by ineiti** [comment]
Will change once @kc1212 finishes the new collection library.

**Comment by kc1212** [comment]
Since blscosi is in and we're trying to push cothority to v3, it's a good time to add all the missing verification functions in Java. After some investigation, the missing functions are as follows, the order is the suggested implementation order.

1. Implement BLS G2 point and BLS G1 point, these are needed for computing BLS signatures.
2. Implement BlsSig class (similar to SchnorrSig)
3. Implement a mask class that produces the correct aggregate for BlsSig and SchnorrSig.
3. Implement a verify function in ForwardLink that uses BlsSig to verify blocks
4. Implement the Trie class (also EmptyNode, LeafNode and InteriorNode), but only enough that we can do existence/absence proofs.
5. Add the existance/absence proofs to the Proof class
