### ISSUE TITLE
ClientTransaction and nonce

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1442]
When sending a `ClientTransaction`, the system needs to make sure that this transaction is not already added to the ledger, else we can have double-spend attacks in the case where a transaction moves coins from one account to another.

It is not feasible to go through the whole blockchain to search if a transaction already has been included once, because the blockchain might get huge.

Ethereum solves the problem by attaching a nonce to each account, and then the request must include a value of `nounce+1` to be accepted.
In OmniLedger we have multiple owners of an instance, so it is difficult to synchronize the `nounce` in case multiple owners want to write at the same time (e.g., loggers sending events to a log-instance).

Another possibility than having nonces in instances is to add a 'header' to each `ClientTransaction` that includes the following information:

- id of last block seen, or index (height) of the block in the chain
- number of instructions

The first instruction signs `( header | hash(inst_0) )`.
The 2nd instruction signs `( hash(inst_0) | hash(inst_1) )`
And all further instruction sign the hash of the previous transaction concatenated with their own hash.

Then the leader decides how old the `ClientTransaction` can be before it is discarded. All followers need to verify the `ClientTransaction` is new, starting from the `last block seen` up to the latest block.

Now the client needs to know which is the current latest block, or which is the index of the currently latest block. If we manage to have a +- accurate frequency of block-creation, the client might even calculate the block-# using `time.Now()`.

**Comment by kc1212** [comment]
For completeness, I want to add the "multiple account" solution that Lefteris proposed.

The problem with ethereum's way of incrementing nonces is that we might have multiple clients speaking to the same instance (e.g., eventlog), so a lot of the transaction might be rejected because the clients don't always know the latest nonce. To fix this problem, we create multiple instances that do the same thing (and have the same darc). This solution allows clients to access any of the instance and send their requests to a random one, which helps to reduce the number of conflicting nonces. Alternatively, we assign each client to different instances such that the load is evenly balanced between all instances. This is a common technique in distributed systems.

I don't have a strong preference on any of these ideas. Both will have a performance penalty. For the services that implement the "last-block-seen" proposal, they will have to check for replays for every new transaction in at least one block, more if the transactions go into a queue, this costs `O(n^2)` where `n` is the number of transactions per block if implemented using the naive algorithm. The "multi-instance" solution won't have significant costs on the service, but clients might occasionally fail to send transactions, depending on how many "replicated" instances there are.

**Comment by ineiti** [comment]
I'm leaning towards the 'blockHeight' solution to make it as simple as possible for clients. But it will surely have an impact on the nodes. We could do what Cristina proposed with regard to adding a bloom-filter to check if a transaction is new or needs to be checked.

**Comment by ineiti** [comment]
Thinking about it again, here is what I propose now:

- `ClientTransaction` holds the following fields:
   - `CreationTime`: unix-nanoseconds since 1970 of creation
   - `InstructionsHash`: hash(inst0 | inst1 | inst2 | ...)
- Each `Instruction` has a signature on the `InstructionsHash` that is verifiable by the darc responsible for this instruction

Some attacks and how they are mitigated:
- DoS by re-sending old `ClientTransaction`s - the leader only allows `ClientTransaction`s in a certain time window (-1 minute, +60 minutes) which reduces the necessary search space
- leader censorship: rotating the leader more than once during the time window
- leader changing the order of the instructions: the `InstructionsHash` prevents this
- leader replacing an instruction by another: the `InstructionsHash` prevents this

The only downside I see so far is this:
- to sign each `Instruction`, the whole `ClientTransaction` has to be known
But in fact this is better than before, because now a malicious client cannot gather signatures for different instructions without showing the context of where the instruction will be used.

**Comment by ineiti** [comment]
OK, yet another proposition:

```
type ClientTransaction struct {
  CTH []byte // The hash of all instructions, without the signatures
  Instructions []struct{
    InstanceID InstanceID // The destination of the instruction
    Version int // Which version of the instance we want to talk to - if it doesn't match, the instruction is invalid
    Spawn Spawn // No changes to current version
    Invoke Invoke // No changes to current version
    Delete Delete // No changes to current version
    Signature Signature // Sign CTH using the appropriate private keys to resolve the DARC rules for this instruction
  }
}
```

This would mean that if you have multiple instructions you need to send the whole ClientTransaction to everybody who needs to sign one or more instructions. Which makes sense, because the signers might want to check whether they actually want to sign the given instruction within the context of the other instructions.

**Comment by jeffallen** [comment]
Here's a difficult counter-example which perhaps shows that this won't work like we expect.

When an eventlog is created, the client sends through a Spawn on a darc which has rule "spawn:eventlog", and a new instance is created. This instance (call it $el) has as a value 32 zeros, indicating that there are not yet any time buckets in the eventlog.

To log an event, the client sends an Invoke on instance $el. The results of running the contract depend on the state of the eventlog:
1. if it is a new eventlog, the following will be emitted: Create "event content", Create "time bucket with time = now and one event in it" and Update $el to point at the new bucket.
2. if the eventlog points at a time bucket with space for a new event, the following are emitted: Create "event content", Update "time bucket, appending new event". Important: instance $el's version is not updated.
3. If the head time bucket should be replaced (too old), then it is like case 1, $el's version is updated.

Implication 1: the $el instance's version might increment or might not increment depending on things that the client cannot predict, and thus the client cannot forecast and correctly set the version field of the Instructions in it's ClientTransaction.

Implication 2: because $el's version is not updated, the replay attack is still possible, at least with respect to contracts like eventlog that have moderately complex behaviour.

**Comment by kc1212** [comment]
@jeffallen raised a valid concern, which means using a version numbers on instances might not be the best way to prevent the replay attack.

The new proposal is the following:
Modify the Instruction struct to include a versions field
```
type Instruction struct {
	InstanceID InstanceID
	Spawn *Spawn
	Invoke *Invoke
	Delete *Delete
	Versions []uint64 // <- new field
	Signatures []darc.Signature
}
```
There is a version number for every holder of a private key. The service stores the version number in special instances where the key is `sha256("public" || pk)` and the value is the version number. These instances are stored in the trie. For every new instruction that the service receives, it must check that the version number for the corresponding signer is one more than the one in the trie. Otherwise the instruction is rejected. The service also provides an API endpoint to retrieve the latest version.

On the client side, the version number become a part of the message for signing. Every holder of a private key must monotonically increase the version number by one when they sign a new instruction. If they do not know what the latest version is, they should request it from the service.

If the instruction must be signed by multiple clients, then the clients should coordinate to set the versions.
