### ISSUE TITLE
Calculate gbar beforehand

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1492]
Currently we calculate `gBar` in `WriteRequest` as `base * skipchainId`, which is problematic, because we know the scalar that brought us to `gBar`.

TODO:
- calculate `gBar` as `Point.embed(skipchainId)` and publish this as part of the configuration of LTS
- use this `gBar` in java

**Comment by kc1212** [comment]
Some questions regarding this issue:

Where exactly does it go wrong if we know the scalar that computed `gBar`? 

If we do the `Point.embed(skipchainId)` approach, it seems everybody knows how `gBar` is computed because everyone knows the `skipchainId`, do we still need to publish it? This wasn't the case before we didn't have a contract for storing the LTS roster, now we do.

**Comment by ineiti** [comment]
Sorry for taking so long to reply. In fact you can only create security proofs if you consider that the scalar of the point is not known. As you write, there is no known attack. But there is a proof that it's secure if you don't know the scalar...

And what you propose with `Point.embed` seems OK. You just need to make sure that the implementations in java and go are the same.

**Comment by kc1212** [comment]
hmm, maybe we do need to add the gBar to the LTS because the embed method is not deterministic in Go
