### ISSUE TITLE
Information stored in state

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1537]
A requirement stated by ByzGen is to have the possibility of following the history of an instance. For this, we would need the following:

- version of instance (also needed for #1442)
- link to previous instance, but:
  - if we link to the block, what to do when there were multiple updates?
  - can we give a link to the clientTransaction that updated the instance? Or even the instruction in the clientTransaction?
- other information needed?
- how do we re-create the state of #n-1, #n-2, ...? Do we need to store some intermediate states? Store the `StateChange`s?
- who is responsible for updating the version of the State? Is it the contract? Or the database?

Depends on the new trie that @kc1212 is working: #1534 and #1542

**Comment by Gilthoniel** [comment]
@ineiti 

https://github.com/dedis/cothority/commit/5f84e8b13ff6132c60a884136874105d535f6cf6

I'm not entirely sure if it's a good idea to have a versioning per instruction compared to per client transaction because the client must in that case increment the version when he uses multiple instructions for the same instance in the same transaction. In the contrary, if the version is per transaction, that means several state changes will have the same version attached.

**Comment by kc1212** [comment]
One client transaction might touch more than one instances. So the version number should be in the instruction because it is attached to only one instance.

**Comment by kc1212** [comment]
Nevertheless, it might be easier to split the "instance version number" feature and the "traversable instance history" feature. Both features are big changes.

The version number one will need clients to sync with byzcoin in case the target instance is modified by another client.

The history feature needs a bit more thinking because, most likely, the client wants snapshots. In that case, I don't see how we can traverse backwards from the latest instance to figure out the state in an earlier time. Because if you overwrite some values, then the original value is lost. Maybe we have to maintain a reference to all the transactions that were responsible for the state change and then replay all the state changes to find a particular snapshot.

**Comment by Gilthoniel** [comment]
Version per state change has been chosen instead of per client transaction because it stores more information and this issue is not related any more with #1442. The problem with version per client transaction is that several state changes can be created for an instance over one tx and we are interested in the state change history so we need somehow to keep the versioning of the state changes.
