### ISSUE TITLE
GetProof Latest block must be chosen based on cdb.getIndex()

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1548]
We've added the idea that the collection knows what index it is updated to (see the call to cdb.getIndex() in updateCollection).

But we have not yet solved the problem that a race between a new block arriving and creating a GetProof reply could result in the latest block returned from GetProof being a different block index than the one the collection was based on at the time the proof was made.

**Comment by kc1212** [comment]
I think the fundamental problem here is that block storage (in skipchain) and state storage (on the trie) happens in two different boltdb transactions. I have two types of solutions in mind

1. trial-and-error, we get the block, and then we get the proof with the index, if the index doesn't match the block index, then try again (but i'm not sure how long we should wait before trying again)
2. we introduce a new rw mutex that locks at the end of the verification function (i.e., we know it will return true) and do a defer unlock in updateTrieCallback. Then, GetProof must get a read lock in order to create the proof

I'm leaning towards the second solution

**Comment by Gilthoniel** [comment]
In byzcoin/proof.go line 35:
```go
for len(sb.ForwardLink) > 0 && sb.Index < c.GetIndex() {
		var link *skipchain.ForwardLink
		// Corner-case when the database is downloading blocks and a proof is
		// requested before all blocks are stored - then we need to make sure that
		// we don't get the latest block, but the block corresponding to the
		// StateTrie.Index
		for height := len(sb.ForwardLink) - 1; height >= 0; height-- {
			link = sb.ForwardLink[height]
			sbTemp := s.GetByID(link.To)
			if sbTemp == nil {
				return nil, errors.New("missing block in chain")
			}
			if sbTemp.Index <= c.GetIndex() {
				sb = sbTemp
				break
			}
		}
		p.Links = append(p.Links, *link)
	}
```
I guess this issue has been fixed ?
