### ISSUE TITLE
Missing a seed for rand.Perm uses in Go

### ISSUE THREAD

**Issue by Gilthoniel** [dedis/cothority#1587]
*Gaylor*
I see we're using rand.Perm for GetUpdateChain to contact a server randomly but I can't find the place where we rand.Seed(n). In the tests it's not random at all but I'm not sure if it is intended to debug more easily ?

*Jeff*
ugh, that’s really bogus (and probably my fault for missing it). thanks for catching it. in general, I’m not very happy with libraries that call rand.Seed, I think that main() should decide when/if/how to call it, so that test code can run with a fixed seed.  So that means we need to add a call to it in conode/conode.go and the same for cothority_template. And somehow, we need to document that if you make your own main.go, then you need to seed rand. Ugh, but the test.sh tests make their own main.go. And probably the same for simulation? I can’t remember. Ugh again.

**Comment by Gilthoniel** [comment]
We might aswell define the random source at the service level. I'm not sure how "secure" it is to change the global seed as you could reseed accidentally. At least if it is at the service package level, you can hide it to external user but still change it for testing purposes

**Comment by jeffallen** [comment]
I looked into integrating this into onet in some graceful way, but rand.Perm() is called from tree.go's RandomSubset, and the only context we have there is the *onet.Roster itself, not a service or protocol or treenodeinstance or whatever.

So I'm going to take the easy/less-magical way out and just put a rand.Seed in each place where we have a main(). However, libtest.sh reuses conode.go, so that turns out to be just one place for servers.

For clients, it's a bit messier, there are lots of main()s. Is hard to figure which ones care about randomness enough to seed it. For now I'm going to not touch them, let's not fix what is not broken.

For javascript, the random numbers are already seeded: https://stackoverflow.com/questions/521295/seeding-the-random-number-generator-in-javascript
The randomization happens via the [shuffle-array](https://www.npmjs.com/package/shuffle-array) package, which uses Math.random.

Finally there's the Java client code, where Roster.sendMessage has "TODO - fetch a random node". So there's not currently any roster permutation in Java at all.
