### ISSUE TITLE
java client Roster.sendMessage always chooses node 0

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1630]
There's a TODO reminding us that we should choose a random server from the Roster.

After fixing this, we need to check that Java unit tests are still stable. If not, we need to solve the underlying problems.

**Comment by kc1212** [comment]
It's not possible at the moment to randomise the node in every type of message due to the counter constraint. For example, the counter is at 0 and the client sets the counter = 1 and send it to a follower, then set counter = 2 and send it to the leader. The leader will see that the counter is 2 and decide it's invalid because it may not have seen the transaction from the follower. A workaround is to disable randomisation when sending transactions. But that's not enough...

The tests that call `getProof` immediately after sending (and waiting) for a transaction fail, too, when using random nodes. That is because we notify that the transaction is included (and respond to the sender) when it is included in the `updateTrieCallback`, which does not mean the transaction is committed to a block on the other nodes. To fix this issue, I think the notification should happen after the call to `StoreSkipBlock` (or `createNewBlock`) returns, because the block commitment is synchronised using the propagation function in skipchain.

**Comment by jeffallen** [comment]
Closing this because we'll wait for it to come up in the context of a real problem, and then the solution will be more clear.
