### ISSUE TITLE
Collecting transactions might loose transactions because of failing nodes

### ISSUE THREAD

**Issue by Gilthoniel** [dedis/cothority#1633]
byzcoin/service.go line 1309
```go
collectTxLoop:
for {
  select {
  case newTxs, more := <-root.TxsChan:
    if more {
...
  case <-protocolTimeout:
    close(root.Finish)
    break collectTxLoop
}
```

After closing the Finish channel, it will close the TxsChan and that will ignore responses from other conodes then if the first one is failiing, that's really bad.

**Comment by ineiti** [comment]
yes, there must be somewhere an issue that describes a more optimal `collectTx` loop where the followers don't delete the transactions when they send it to the leader, but they only delete the transactions once they see them in the block. 

Which will be a bit difficult if we get an optimized collect-loop, because then the followers might get a request for new transactions before they see the new block, depending on how the collection-loop is implemented.

**Comment by kc1212** [comment]
duplicated of https://github.com/dedis/cothority/issues/1337 closing
