### ISSUE TITLE
java.darc.EvolveDarc checks

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1635]
verify if the new darc passed has the same `baseID` as the current darc and throw an exception if not.

**Comment by kc1212** [comment]
We do check the base ID in `evolveDarcInstruction`:
```
    public Instruction evolveDarcInstruction(Darc newDarc, Long signerCtr) throws CothorityCryptoException {
        newDarc.increaseVersion();
        newDarc.setPrevId(darc);
        newDarc.setBaseId(darc.getBaseId());
        if (!newDarc.getBaseId().equals(darc.getBaseId())) {
            throw new CothorityCryptoException("not darc with same baseID");
        }
        if (newDarc.getVersion() != darc.getVersion() + 1) {
            throw new CothorityCryptoException("not darc with next version");
        }
        Invoke inv = new Invoke("evolve", ContractId, newDarc.toProto().toByteArray());
        byte[] d = newDarc.getBaseId().getId();
        return new Instruction(new InstanceId(d), Collections.singletonList(signerCtr), inv);
    }
```

But the way we evolve darcs is quite strange. Firstly, we set the baseID in that function so it's not possible to throw the "not darc with same baseID" exception. Secondly, we have to set the the version number to be a number that's equal to the old Darc, so that we can increment it in the function above. It's probably best to clarify what attributes the caller has to set. I suggest we ask the caller set everything except the version, prevID and baseID, because these can be derived directly from the old darc.

**Comment by ineiti** [comment]
Yes, evolving darcs is quite strange, I agree. Currently you have to do something like:

1. copy the darc
2. update the rules
3. call 'evolveDarcInstruction'

But I don't see how to do it in a more proper way :(
