### ISSUE TITLE
Port JVSS to SDA framework

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#164]
First porting of a application to SDA.

**Comment by nikkolasg** [comment]
Already have some comments about the SDA structure:
* SDAData is not a good name because in the apps it becomes: sda.SDAData ... A bit too much, don't you think ?
* I now more than ever think the automatic aggregation of messages is inducing way more complications than "helpfullness". Indeed, each time in "Dispatch()" we have to write a "for loop" for each kind of message. 
```
switch msgs[0].MsgType {
    case Request:
         for sda := msgs {
             m := sda.Msg.(Request)
             ...
          }
    case Response:
         for sda := msgs {
             m := sda.Msg.(Response)
             ....
         }
    if EnoughMessage() {
         Finalize()
    }
 }
````
These "for" loops are creating clearly more code than a simple 

```
Dispatch(msg *SDAData) {
    switch msg.MsgType {
       case Request:
          req := msg.Msg.(Request)
          doRequest(msg)
       case Response:
           resp := msg.Msg.(Response)
           doResponse(msg)
    }
    if EnoughMessage() {
          FinalizeStuff()
    }
}
```
The "EnoughMessage" method is clearly needed in both cases anyway, we can't trust only number of messages, but the number of differents senders. Also from an external point of view, there are some interpretations that can go wrong: 
    * we can see it as "here are all the messages" ... clearly not ! 
    * It also sounds very strange  to verify the types of message using "msgs[0].MsgType", I  don't feel safe because I am always afraid that the rest is not of the same type. 
    * What about timeout / non-responding peer ? How to still get the message even if we don't have all of them since there is one peer that do not response ? 
    * Speed ! The original idea was to still use the "Round" interface but I think we should change that interface because it would be clearly more efficient to treat each incoming message as they arrive instead of taking them all at once !  And it's not more or less complicated than batching them all. 
It's true that we did not added the configuration option to NOT aggregate, so we have to talk about that more in-depth.

Others comments :
* We have to think better (i.e refactor ? add helper?) about our "overlay". Searching in the tree each time we want to send something is clearly not efficient (refer to SendSDAToTreeNode)
* We should CLEARLY document wether Start or / and Dispatch are called in seprate go routines or not. For my part, I'd call Start()  in separate go routines each time. For example in JVSS, when a node starts, he must first create with the others peer a longterm random secret. He does that in Start() of course, and that takes time.Start() for me clearly states "we start the protocol and we will do a lot of stuff". On the other hand, Dispatch can be called in the main thread, as long as we clearly document it that it may be a bottleneck if you do big operations. It would be best to call it in a separate go routine but I am afrait that there will be too much pressure on Host on the long run,since Dispatch is often called. But that's only my opinion... ;) As long as we clearly say it somewhere visible it's fine.

**Comment by Daeinar** [comment]
From what I am experiencing currently with implementing RandHound, I agree with @nikkolasg's observations above and especially regarding the multi-message issues (for loops, consistent message type verification, did we receive all messages? etc.). If that could be simplified / be made more robust, it would be clearly a benefit.

Just my 2 cents.

**Comment by ineiti** [comment]
Is there a way to have a helper function that takes a `[]*SDAData` and a `ResponsMsg` to return either an error (non-consistent array) or an array of `ResponsMsg`? And do this for any type of array?

Perhaps

```
var ResponsMsgs []*ResponsMsgs
ResponsMsgs, err := ReadMsgs(SDAData, ResponsMsgs{})
```

or such? Would that help?

**Comment by nikkolasg** [comment]
Any protocols can do that but not us since we don't know the type of message they are using beforehand. It would be possible in others languages but not here.

**Comment by Liamsi** [comment]
> SDAData is not a good name because in the apps it becomes: sda.SDAData ... A bit too much, don't you think ?

Agreed, but we could (and probably should) refactor this at the very end

> we can see it as "here are all the messages" ... clearly not ! 

My first though when I saw `EnoughMessage()` was: there is an 's' missing to indicate that we recv'd all messages ... Also agreed.

> It also sounds very strange to verify the types of message using "msgs[0].MsgType", I don't feel safe because I am always afraid that the rest is not of the same type

Also agreed. But @ineiti's idea he posted in slack: wouldn't it solve the above problem (and maybe some of the other mentioned?).

> What about timeout / non-responding peer ? How to still get the message even if we don't have all of them since there is one peer that do not response ? 

Good point. This should definitely be possible. Wouldn't this make *necessary* to dispatch the messages message by message instead of all together as an array?

>  Speed ! The original idea was to still use the "Round" interface but I think we should change that interface because it would be clearly more efficient to treat each incoming message as they arrive instead of taking them all at once ! 

If most use-cases can process the messages directly (without waiting for the rest), this is a good argument. But don't all protocols wait for all messages to arrive (from the children) to work with them (at least the way upwards)?

From what I understand, the big question (besides all the smaller comments) here remains: Do we *need* a dispatcher for single messages instead for a array/slice of messages or is it just a question about style?

**Comment by nikkolasg** [comment]
>If most use-cases can process the messages directly (without waiting for the rest), this is a good argument. But don't all protocols wait for all messages to arrive (from the children) to work with them (at least the way upwards)?

Of course, protocols would preferably need all the message before going further but that is not the problem here. The problem is that every protocols could directly process each messages,i.e. "small" computation steps, as they are coming, and when there is enough, they go further. Instead of waiting all of the messages to be here, and then make one "big" computation step that could clearly be a bottleneck when a protocol must process > 100, 1000, 10000 msgs.

>It also sounds very strange to verify the types of message using "msgs[0].MsgType", I don't feel safe because I am always afraid that the rest is not of the same type

>Also agreed. But @ineiti's idea he posted in slack: wouldn't it solve the above problem (and maybe some of the other mentioned?).

Yes it does solve **this** problem. I also like to use reflect, and nice trick like this but for me it still reminds me the citation @ineiti  likes : " The competent programmer is fully aware of the limited size of his own skull. He therefore approaches his task with full humility, and avoids clever tricks like the plague.". Again, if we include this trick, it again induces some more complexity: what do we do when there is an error and the type are not all the same ? Can we still get the messages ? Do we drop them ?

>What about timeout / non-responding peer ? How to still get the message even if we don't have all of them since there is one peer that do not response ?

>Good point. This should definitely be possible. Wouldn't this make necessary to dispatch the messages message by message instead of all together as an array?

I'm sure we can also think of something using configurations between SDA and Protocols so it is not ***necessary*** but it adds another layer of interaction, of complexity (one more function / config name to learn). The same is true with the configuration option of choosing *"do i want my messages aggregated or not"* (still not implemented yet). It seems to me we again try too much to implicate sda in what the protocol wants to do. For example, what if the protocol wants to use some clever/stupid rules like exponential waiting for absent peers or whatever, instead of a simple timeout ? The more we do things for the protocol, the less he is able to do his own things.

>From what I understand, the big question (besides all the smaller comments) here remains: Do we need a dispatcher for single messages instead for a array/slice of messages or is it just a question about style?

Except for the for-loop, my other comments are not about style, but style **is** important also for a public API.

**Comment by ineiti** [comment]
Just to cite another proverb (Chadian this time - I’m getting ready for my travel ;)

œn yikhaff, iiden talaff - The eye is afraid, the hands break.

I will give you the explanation tomorrow ;)

**Comment by nikkolasg** [comment]
Another comment:
 + Maybe we should remove the Start() function in the ProtocolInstance interface. I thought initially it would be useful, so sda can directly start a protocol, but in fact, it's the users most of the time that wants to start the protocol using one specific function, so they can get the results out. For example in JVSS, I'd ideally do stg like:
``` 
jvss := jvss.NewJVSSProtocol(....)
// we just add it to its regsitry of protocol instances
sda.AddProtocolInstance(jvss)
// equivalent of jvss.Start() but I can get the result here, and also I know when it is finished etc. 
longterm := jvss.SetupDistributedLongterm()
````

For now, in the test, the way I've found is to make another struct:
````
type CustomJVSS struct {
    jvss.JVSSProtocol
    schnorr ...
}
 ...
sda.RegisterProtocolInstance( ....) {
    c := CustomJVSSProtocol{
       jvss: jvss.NewJVSSProtocol(...),
       schnorr: ...
    }
    return c
}

func (c *CustomJVSSProtocol) Start() {
    schnorr := c.jvss.Start() 
    c.schnorr  = schnorr
}
```

This is quite ugly I think. This comment is also taking place in the debate about *how to design the protocols interaction*.

**Comment by ineiti** [comment]
Done
