### ISSUE TITLE
Java library doesn't check the hash of received blocks

### ISSUE THREAD

**Issue by Gilthoniel** [dedis/cothority#1703]
Data of the block is accessed but the hash is never calculated to make sure it hasn't been forged. One simple example is the proof verification that only checks the forward links.

**Comment by kc1212** [comment]
this might be true on the go side too, see `byzcoin/proof.go:Proof.Verify`

**Comment by jeffallen** [comment]
I am removing this from planning for v3 for the moment, because it's not clear how far we need/want to push this verification into the Java client code. I.e. should the caller be responsible for remembering the last known trusted skip block? Should Proof.verify() call getSkipblock multiple times to run back to the last known block? etc.

**Comment by Gilthoniel** [comment]
For the Proof.verify(), you get a proof from the genesis block which is a known ID to the block containing the requested instance. That means if you validate the forward links until the latest block, it should be enough to check the announced hash is correct according to what is received from the proof.

**Comment by Gilthoniel** [comment]
SkipchainRPC is doing the check on getUpdateChain
