### ISSUE TITLE
Unprotected Instructions for darc-only signers

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1742]
https://github.com/dedis/cothority/blob/master/byzcoin/replayguard.go#L60

Indicates that if there are `darc` signatures, they are not replay-protected, which makes sense. But now there is a *feature* of having non-replay-protected instruction, if an instruction has only darc-signatures. It helps me with one of my projects in personhood, so I'd prefer to keep it, but is this intended behaviour? Or should

https://github.com/dedis/cothority/blob/master/byzcoin/transaction.go#L262

verify that there is at least 1 `SignerCounter` present?

**Comment by kc1212** [comment]
The signature should always be from a concrete identity, that's why we return an error if it's not the case.

For example, if you delegate a rule like "spawn:darc -> darc:xyz", and pk1 is allowed to sign for "darc:xyz", then pk1 will create a signature and add its own identity to satisfy the "spawn:darc" rule. So darc-signatures are just ordinary signatures, it's how the expressions are evaluated that changes (we have to traverse the "delegation path"). `byzcoin/service_test.go:TestService_DarcDelegation` tests this by creating a new rule with a darc ID as the expression. We still have to increment the signer counters so these should be replay-protected.

**Comment by ineiti** [comment]
OK, makes sense. Now I get it. Closing this issue, as it's not relevant.
