### ISSUE TITLE
Deferred contract: index out of range with rst.GetIndex()

### ISSUE THREAD

**Issue by nkcr** [dedis/cothority#1938]
I found an edge case where getting the current index with `rst.GetIndex()` returns `runtime error: index out of range`. This happens on the deferred contract there : https://github.com/dedis/cothority/blob/master/byzcoin/contract_deferred.go#L343

It happens when invoking a deferred instruction with a deferred contract, for example performing a deferred `invoke:deferred.addProof` with a deferred contract... still there? Here is an example:

Code to reproduce the error:

```bash
# Add the rules
bcadmin darc rule -rule spawn:value --identity <admin id>
bcadmin darc rule -rule spawn:deferred --identity <admin id>
bcadmin darc rule -rule invoke:deferred.addProof --identity <admin id>
bcadmin darc rule -rule invoke:deferred.execProposedTx --identity <admin id>
# Spaw a deferred value contract
bcadmin --export contract value spawn --value "Hello world" | bcadmin contract deferred spawn
# Perform a deferred addProof on the previous deferred value contract
bcadmin --export contract deferred invoke addProof --hash <hash> --instid <inst id> | bcadmin contract deferred spawn
# Add proof on the second deferred contract
bcadmin contract deferred invoke addProof --instid <inst id 2> --hash <hash 2>
# Exec the deferred addProof
bcadmin contract deferred invoke execProposedTx --instid <inst id 2>
> runtime error: index out of range
```
.
  
@kc1212 you helped me implementing this `rst.GetIndex()`, do you have an idea how to fix this?

**Comment by kc1212** [comment]
is there a stack trace for this problem? or it's just an error message

**Comment by nkcr** [comment]
Apparently, this is related to `dfs` not saving metadata: https://github.com/dedis/cothority/blob/master/byzcoin/trie/trie.go#L579

**Comment by kc1212** [comment]
Thanks, I'll take care of this issue.

**Comment by kc1212** [comment]
I'm revisiting this issue and I'm not sure what can be done about the `ForEach`. It is not designed to iterate through the metadata and I'm not sure if it should. If it does then the caller may be confused and interpret metadata as the real key/value pairs in the trie. As such, `ForEach` shouldn't be used to copy the whole trie so maybe `err = rst.ForEach(sst.Set)` in the deferred contract should be something else.

The reason deferred contract can't use the read-only trie is because it needs to simulate the execution of new transaction using `sst.StoreAll`. Using `StoreAll` means it will modify the existing state, but what if we expand the interface and introduce `TryStoreAll(scs StateChanges) (ReadOnlyStateTrie, error)` which does not modify the existing read-only trie but returns a new one that could be used in the next iteration. The new trie will have the same reference to the disk-backed trie but with a new overlay of key/value pairs. This way, we don't need to copy all the key/value pairs in the contract. What do you think @nkcr? 

(`TryStoreAll` is not the best name, I'm open to suggestions.)

**Comment by kc1212** [comment]
Maybe `StoreAllToCopy` or `StoreAllToReplica`

**Comment by kc1212** [comment]
Here is the implementation https://github.com/dedis/cothority/pull/2019

**Comment by nkcr** [comment]
In order to have greater flexibility and do less copies, instead of adding `StoreAllToReplica`, why not adding a `GetCloneOfStaging() *stagingStateTrie` ? 

With this we only copy the stagingStateTrie once at the beginning (instead of doing it for each instruction in the proposed transaction) and we can use this copy for all the operations.

**Comment by kc1212** [comment]
I thought of this option but I didn't go for it because a mutation in the returned `*stagingStateTrie` may change what's in the original `ReadOnlyStateTrie`. That is, when you do a `Commit` in `*stagingStateTrie` then the disk-backed part of the `ReadOnlyStateTrie` will be updated. I feel it's not very nice when there is a way to work around the read-only data structure and mutate it.

**Comment by nkcr** [comment]
Oh, I see. Then lets go for #2019
