### ISSUE TITLE
TwistPoint and lineFunctionAdd does not use GFpPool

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1945]
Follow-on to #1877.

@yanngabbud ran the same profile and has noted that garbage went down, but the Miller test is still creating a lot of TwistPoint objects, which each create 4 GFp2's. We need to have a TwistPoint constructor that uses the GFpPool.

Another `new TwistPoint()` that might be able to use the pool is in G2 unmarshal.

There are also places in OptAte.java like line 84 where the pool is easily available, but there is still a `new GFp2()`.

Please keep using the pool.

**Comment by nkcr** [comment]
Using a cache is interesting because we can release objects that a no longer needed by putting them back into the pool and re-use them later. This is particularly interesting for temporary objects.

In the constructor however (as well as in the other places you mentioned) we don't know when those objects will be released, so we can't put them back into pool and re-use them later. This will only empty the pool and create new objects if the pool is empty.

It's even worse to use the pool when we don't release later since, even when those objects won't be useful anymore, they won't be garbage collected because they will still be reference in the pool.

Is it right @kc1212 ?

**Comment by jeffallen** [comment]
In `lineFunctionDouble`, t and t2 have a lifetime of the function, they do not escape in the result. Which means that they could come from the pool and go back into the pool.

If we can track the lifetime of the TwistPoint, we can have it put the GFp2's inside itself back into the pool; but the lifetime of the TwistPoints used in the miller algorithm currently crosses the calls to lineFunctionDouble and lineFunctionAdd.

So what if lineFunctionDouble and lineFunctionAdd were methods on the object called "result"? Then there would be one result created at the top of the loop on sixuPlus2NAF, and it would be reused and updated through the whole loop. (Getting this change right looks a bit more difficult than just looking for short-lifetime GFpX's to cache.)
