### ISSUE TITLE
`bcadmin link` shows phantom chain after darc evolve

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#2028]
Seen while debugging NativeScript app. To repro:
* create new ledger
* call GetAllByzCoinIDs, expected result == 1 chain
* evolve the genesis darc
* call GetAllByzCoinIDs, expected result == 1 chain, actual result 1 known chain and 1 unknown chain

**Comment by ineiti** [comment]
That's because `byzcoin.GetAllByzCoinIDs` has probably been copied from `skipchain.GetAllSkipchains` which returns all skipblocks erronously. While fixing `GetAllSkipchains` it has been decided that it is left with this error for backward-compatibliity. But there is a deprecation warning in the comment, and that it will be removed in `v3` ;)

The correct method to use would be `GetAllSkipchainIDs`, which calls `SkipBlockDB.getAllSkipchains()`. Unfortunately that method is private and thus not exported.

Proposed fix: export `SkipBlockDB.getAllSkipchains()`, which is a backward-compatible change, and use that one in `byzcoin.GetAllByzcoinIDs`.

**Comment by Gilthoniel** [comment]
Almost right, it's actually the public function that was using the old private call that is buggy.

**Comment by ineiti** [comment]
Right - this makes me think of the following project, that unfortunately never continued:

http://cs.brown.edu/~spr/codebubbles/

I thought it would be really nice to have a more 'context'-aware editor, that lets me see what I'm actually working on and what the paths are. Then I would have had an easier time getting my comment right ;)

That might be a nice semester project: writing a plug-in to IntelliJ that shows the program in this 'bubbly' view...
