### ISSUE TITLE
More versioning issues

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2134]
https://www.npmjs.com/package/@dedis/cothority has been released at version 3.1.8, however:

* https://github.com/dedis/cothority/blob/master/external/js/cothority/package.json still has `3.1.7` in "version"
* https://www.npmjs.com/package/@dedis/cothority/v/3.1.8 doesn't have the method `ourGame` in `personhood/RoPaSciInstance`, while https://www.npmjs.com/package/@dedis/cothority/v/3.1.8-p1910.3012.3304.0 does have it

My guess is that there is a `3.1.8` branch somewhere, and that the automatic deployment of npm packages - the `3.1.8-p1910...` - succeeded, while the manual deployment for some reason deployed an old version.

**Comment by jeffallen** [comment]
The JS versions are uncorrelated with the Cothority versions, except for the first digit. So to find @dedis/cothority@3.1.8, go look at the tip of the v3.3.x branch.

ourGame was added in commit 64c2a9ec05, which was not marked for back porting to v3, so it wasn't.

I'm not saying this is ideal or easy to deal with, but it's the unavoidable consequence of releasing JS from the same repo as cothority, and of continuing to develop new stable code after starting the "unstable" part of the development cycle.

The shortest path to solving your problem is to back port 64c2a9ec05 to v3 and release a new Cothority-JS. Which is what I'll start doing now.

**Comment by jeffallen** [comment]
Fixed in https://www.npmjs.com/package/@dedis/cothority/v/3.1.9

**Comment by ineiti** [comment]
OK - Thanks for the explanation. I forgot to look at the 3.3.x branch, now it makes sense. Even though I don't understand where the '3.1.8-p...' came from...

**Comment by jeffallen** [comment]
The pre-releases are coming from travis, please investigate those with @tharvik , because I have no idea how that works.

**Comment by tharvik** [comment]
> I'm not saying this is ideal or easy to deal with, but it's the unavoidable consequence of releasing JS from the same repo as cothority, and of continuing to develop new stable code after starting the "unstable" part of the development cycle.

You can use npm tag to have a concept similar to branches, keeping a stable version to tag "v3" and a newer one with "v4".

> Even though I don't understand where the '3.1.8-p...' came from...

Before publishing, `npm version prerelease --preid=p$(date +%y%m.%d%H.%M%S)` is executed inside external/js/cothority, which bump the patch version (ie 3.1.7.to 3.1.8) and put the ~date at the end (to avoid name clashing on npmjs.org); as the deploy is set to run when it's merged to master, it follows the state of master and not the 3.3.x branch.

**Comment by ineiti** [comment]
Now it all makes sense. Thanks for helping me understand it!

If only I could say the same thing about life in general ;)
