### ISSUE TITLE
Level0 forward-link missing in 52947

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2357]
from @jeffallen :
```
So I wanted to traverse the entire production skipchain offline to check kyber #434 
against it, and I found that replay stops at block 52944 with this error:
Warning for block 52944: bad forward-link 1/3: to-field points to non-existing block
Successfully checked and replayed all blocks.
4:17 PM
(that’s a lie, there are over 80k blocks!) (edited) 
4:21 PM
gaylor.bosson Isn't it only a warning meaning it used a different link to move forward ? 
4:28 PM
jeff.allen No, it’s failing to walk the chain past 52947 because it has no forward links. 
Corrupted. :disappointed: (edited) 
4:48 PM
jeff.allen Well, I’ve got to go now, but I plan to find a solution for this, I’d like to see if 
it can be lower-cost than the other things we’ve done in the past, i.e. “bcadmin db 
fetch”, where we go fetch one single set of forward links in order to fix a db.
11:13 PM
jeff.allen So I’ve currently got dedis.nella.org offline to repair it. Using “db replay” 
I found that it didn’t have correct level 0 forward links out to the end of the chain, 
and so I used “db catchup”, which seems to have worked ok, though the majority 
of the blocks I downloaded allegedly came from “dedis.nella.org”, which was 
impossible, because my server was down. 
So something is not right in “db replay” logging, still looking for what.
11:14 PM
I am now running the replay again, hopefully it will go out to the end of the chain this 
time. (edited) 
12:53 AM
jeff.allen It is repaired and back up. It looks like tls://conode.c4dt.org:7780 is down 
right now. Also, I got some feedback from the catchup that gasser.blue might 
have missing 0 level links as well.
```

Todo:
- [x] check the logs in `bcadmin` to see why it says it got the blocks from itself
- [x] "db catchup" did not terminate on it's own; it got to the end of the chain and then got into a loop of asking other servers for confirmation

**Comment by jeffallen** [comment]
Actually the "replay forward links" thing is just not really useful, because if you run "db catchup" on a DB which terminates before the rest of the cothority because of missing 0-level forward links, then catchup does the right thing: it find the end of the local database, and then does a catchup from there, fixing the missing 0-level forward link, and then going on through the rest of the chain.

But I added another item above: the end of the catchup was not graceful, I had to hit ctrl-c.

**Comment by jeffallen** [comment]
I wrote this up and almost deleted it because I'm just not sure it's true or helpful, but I decided to leave it here anyway, as food for thought:

I think `bcadmin` is lying about which server replied because is uses gbMulti -> GetUpdateChainLevel -> SendProtobufParallel, which will only contact one server if UseNode has been called before. But it's not clear to me that UseNode is always called before, and with the same index as is used to print the name of the server we supposedly just contacted.

**Comment by ineiti** [comment]
Did not do the following:

- [ ] add `replay forward-links` to `bcadmin` that only checks the forward-links without replaying the content of the blocks

Couldn't reproduce the <ctrl-c> at the end of the catchup - probably because it's trying to contact a node that is down and the timeout is somewhat long...
