### ISSUE TITLE
cothority consensus algorithm

### ISSUE THREAD

**Issue by liorko87** [dedis/cothority#2450]
If I understand correctly, cothority uses Proof of Vote (PoV) as the consensus algorithm.
Can you point me to the direct location of the consensus algorithm implementation?

**Comment by ineiti** [comment]
The cothority is the sum of all protocols and services. You're probably interested in the `byzcoin` service, which uses the `byzcoinx` protocol for its consensus. We call it `Proof of Authority`, because the list of nodes is fixed by a set of administrators.

So you can look at the byzcoinx protocol in the cothority.
