### ISSUE TITLE
Lint our code

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#269]
Make sure all code is run through `golint` in Travis. Discuss what options we want to fail on.

**Comment by Liamsi** [comment]
I looked into the golint code: Unfortunately, you cannot manually set what to lint and what not. Furthermore the API for linting consits of unexported functions: https://github.com/golang/lint/blob/master/lint.go#L172-L190

One easy way to still have linting, would be to fork the linter and only enable the lints we need.

**Comment by Liamsi** [comment]
Another way would be to use `grep` as a kind of white list (probably easier) I will see if this (still) returns too many false positives.

**Comment by nikkolasg** [comment]
"In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process." [1](https://github.com/golang/lint)
The day where golint proposes us something bad, what do we do ?
do you think we are self-disciplined enough to do it ourself when coding AND reviewing a PR ?

**Comment by Liamsi** [comment]
> do you think we are self-disciplined enough to do it ourself when coding AND reviewing a PR ?

I thought so. But we have so many undocumented exported functions [1] even in interfaces that have been merged during code reviews. To me it looks like some automated help can't harm. Another way to achieve at least documented exported functions, would be to turn on golint in your editor (that way you decide what to ignore and what not; instead of letting `grep` decide)

> "In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process." 

I know. But we could still use it for one particular lint: Reminding you of uncommented exported functions. It doesn't mean, we do not need to review and actually read the comments. An automatic tool might beat the best human go-player but it still can't tell if the existing comment makes sense ;-) 

[1] Currently, there seem to be around 261 uncommented, exported functions (`golint ./...| grep " should have comment or be unexported" | wc -l`)

**Comment by ineiti** [comment]
I do like the idea of having a whitelist of things to grep and then do something like

```
if lint | grep -q (one|two|three); then
  echo Lint failed
  exit 1
fi
```

**Comment by Liamsi** [comment]
OK. I will add something like this to travis. Please make sure to review all comments then. If we start writing comments etc., just to silence the linter, this would be counter productive (in my opinion, no comment is better/more honest than a bad, misleading comment for instance)
