### ISSUE TITLE
Refactor the packet-format

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#287]
For the moment the `Host/Overlay`-packets are embedded as a binary blob in the `lib/net`-packets, which can make it difficult to redo the same in another language.

Is there a way to send both packets one after the other? Or another solution?

**Comment by nikkolasg** [comment]
This issue should be resuscitated in regard with #680 . 
I think this issue should aim to have a clear definition of each packets used by Cothority and not having something like:
```
type OverlayMessage struct {
 // overlay fields 
 // ...
 // protocol message
 message []byte
}
```
because then message is completely a byte array without any meaning and does not use any of the advantages of protobuf (extensions format, compatibility etc).
Clear to me means:
```
type CoSiPaket struct {
   // Cosi messages
   Announcement
   Commitment
   Challenge
   Response
   // overlay messages / fields
   OverlayPacket
}
type OverlayPacket struct {
   // overlay fields ...
}
```

**Comment by nikkolasg** [comment]
This issue is currently being resolved (PRs will come). Here's a check-list of things to do in order to be able to describe a clean wire protocol format for the RFC (#680) :
- [ ] Change the packets sent through the networks according the scheme described above.
- [ ] Change the uuids used to distinguish the different messages at the network level into something simpler such as `uint16` or `uint64` etc. This would be really neat to have so we don't have to compare 16 bytes just to know the type of the message.
- [ ] Generate the proto files definitions for all packets used by CoSi.

**Optional** (but at the same time **essential** to make sure we did not mess up):
- [ ] Implement a alternative implementation of CoSi in another language

**Comment by nikkolasg** [comment]
# Wire protocol ID related problems

One problem that keeps occuring when designing the library is how to represent a
packet, a certain structure, or simply like a "hash" which is not necessarily known 
at run time. In the cothority code, this problems happens in the network library
and the sda library.

# Network library

## Packets

For the moment, each packet we send through the network is preceded by the size
of the encoded packet and then it's "PacketTypeID" which is an UUID v5
(https://www.ietf.org/rfc/rfc4122.txt).

In details, to generate the id of a specific Golang struct, we generate a UUID
v5 with:
* the namespace being the Namespace URL
  (https://stackoverflow.com/questions/7724903/where-do-uuid-namespaces-come-from)

* the "value" (the value to hash) being:
    `https://dedis.epfl.ch/ || protocolType/ || reflect.TypeOf(packet).String()`

Two potentials problems with this approach:
 * `reflect.TypeOf(packet).String()` is very Golang specific (this issue has already
   been raised but can't find the link again) and returns
   something like `packageName.StructName`. It already happened that we changed
   the name of a struct, that means the resulting ID will be different and will
   be incompatible with any previous or alternative implementations.
 
 * Even if there is nothing particularly outstandingly wrong with designing our
   protocol this way, it seems more complex than *needed* and not really "readable"
   nor "memorizable".
   
A simple unsigned 2 bytes number, independant of the name of the struct seems
largely sufficient and more readable. In the same spirit of the "TLS Suites"
numbers or the Packet Type in OpenPGP headers. 
THIS REQUIRES CHANGES IN THE CODE FOR EVERYONE, NOT ONLY PROTOCOL.

## Server Identity

A Server Identity contains the longterm public key and an address. We designate
a specific ServerIdentity by its ID in many of the subsequents structures. The
ID of a ServerIdentity is generated as a UUID v5 :
 * namespace is the Namespace URL
 * the "value" is
   `https://dedis.epfl.ch/ || id/ || publicKey.String()`

One potential problem here is that we take the hexadecimal value of a public
key which is not clearly defined as little endian or big endian. The fact that
it is in hexadecimal is also hidden. That should at least be specified. 

# SDA library

## Roster

A Roster is a list of  ServerIdentity and can be identified by its ID. The ID of
a Roster is simply a UUID V4 which returns a randomly generated value. 

A potential problem with this approach is that any implementation that does not
know the ID of a Roster it's using (let's say it creates it) will, in regards to
others implementations, have created a NEW ROSTER, but both contains the same
data. 

A simple solution would be to switch to a V5 UUID and include the ordered UUIDs
of each ServerIdentity inside, as to make it unique per list of ServerIdentity.

## TreeNode

A TreeNode is a node of a Tree and contains a parent TreeNode (if not root) and
some children TreeNode (if not leaf). It is designated with an UUID V4 (random). 

## Tree

A Tree contains a Roster and the root TreeNode. It is designated by a UUID V5 
 * namespace is the Namespace URL
 * the "value" is
   `https://dedis.epfl.ch/ || tree/ || roster.ID.String() || root.ID.String()`

One potential problem with this approach is that it's possible to define
multiple trees with the same ID as long as they use the same roster and root
node. 
One solution would be to include the "whole" tree in a ordered BFS style into the 
ID so that each Tree ID is unique.

## Token

This structure contains many tokens. 
```
type Token struct {
	RosterID RosterID
	TreeID   TreeID
	ProtoID   ProtocolID
	ServiceID ServiceID
	RoundID   RoundID
	TreeNodeID TreeNodeID
```

These were added because of our current architecture of SDA. 
Potential problems/observations:
 * our current architecture still allow protocols to run independantly 
 without services, and to have service launch protocols so we need to distinguish 
 both cases that's why we have `ProtoID` and `ServiceID`.
 The problem here is that we define MORE informations that is needed *just
 because* we coded our framework this way.

 => Ideally, for protocols/service we (well, I) wish to define a full wire protocol
 specifications, we should not need to have both, but only one "ProtocolID".
 
 * a ProtocolID is a UUID V3 (!) version with
   + namespace being NamespaceURL
   + value being: `https://dedis.epfl.ch/ || protocolName/ || protocolName`

   We should at least put it a v5 to be consistent.

# Open questions

Should we stick with UUID ? Should we stick with our own *namespace* ? 

# Conclusions

There's some stuff to fix, some that requires little change to the code base,
and some that requires changes everywhere. I belieave that all of theses changes 
would bring a much cleaner and readable wire protocol.

**Comment by Daeinar** [comment]
Some questions:
1) Why do many of the name space elements end with an `/` (e.g., `protocolName/`)?
2) Why is the address to generate the server identity an actual url (i.e., `https://dedis.epfl.ch/` in the above example)? Shouldn't that be rather a combination of ip address and port number, as some servers might not have an associated domain? Or does the url only identify the cothority the server belongs to, i.e. the namespace you are mentioning, and if so would it make sense to allow arbitrary strings there (again some cothorities might not have a url attached to it)?
3) Nitpick: I would also try to be as explicit as possible when specifying variables and their values, e.g., again in the server identity category above write `ServerID = https://dedis.epfl.ch/ || id/ || publicKey.String()` instead of 
> the "value" is
> https://dedis.epfl.ch/ || id/ || publicKey.String()
4) Would it make sense to include a time stamp of the tree creation into the `TreeID`, regarding: 
> One solution would be to include the "whole" tree in a ordered BFS style into the
> ID so that each Tree ID is unique.

I am not sure how relevant the above questions are since the architecture might chance anyways.

**Comment by nikkolasg** [comment]
To answer to 1) and 3):
An UUID V3 or V5 is composed of a *namespace* and a hash value. In all my descriptions above, I decomposed the UUID by giving first the namespace, and then the value that will being hashed, so saying `ServerID = ...` is wrong, it's more like `ServerID = UUID.V5(namespace, value)` where `value = https://dedis.epfl.ch/blabla`.
We used our own namespace I believe in the generation of UUID v5 inside the `value` parameters, that's why we also have these `/` in the value.

To answer 2):
Yes, I believe this should be the correct approach indeed. This would be much simpler.

To answer 4):
I don't think it's what we want because if two nodes create the same tree at different intervals, they **will** have to exchange both trees over the network since their time have changed. It's more likely that we would want to have a **bijective** mapping between `TreeID` and `Tree` where a `Tree` can be seen as a list of `ServerIdentity`.

Does that answers your questions ?

**Comment by Daeinar** [comment]
@nikkolasg: Yep it does, thanks for the clarifications.

**Comment by ineiti** [comment]
Is it possible to have a split system, where the wire-defined protocols have their own namespace, but we continue using our protobuf-uuid-namespace for the not-wire-defined protocols? Like your proposition of having a 16-bit identifier for the protocol, and id=0 is used for the current system, while ids>0 refer to wire-defined protocols.

**Comment by nikkolasg** [comment]
> having a 16-bit identifier for the protocol, and id=0 is used for the current system, while ids>0 refer to wire-defined protocols.

That's actually a pretty cool idea to keep both codebase working (while we do a transition)!!
Having a `0` exception saying it's completely golang-specific is something I'm OKAY to have if it permits to make most of the others change possible...

**Comment by Daeinar** [comment]
To summarise the potential changes:
1) **Packets:** Introduce 2-byte identifiers of the wire-format to distinguish different messages.
2) **Server Identity:** Fix endianess of the hexadecimal representation of the public key.
3) **Roster Identity:** Update to UUID v5 and include an ordered list of the server identities to make it unique.
4) **TreeNode Identity:** Update to UUID v5 (for consistency)?
5) **Tree Identity:** Make it unique, e.g., by including the whole BFS-ordered tree.
6) **Protocol Identity:** Update to UUID v5.
7) **Tokens:** Decide what interactions between regular protocols and services are required and based on that clean up the information stored in the token struct.

Anything I forgot?

@ineiti: I also like your proposal of having `id = 0` to identify the current system and `id > 0` for protocols that already have a wire definition. Once we made the switch to the new format we can still keep the `id = 0` for other exceptions that might be needed in the future.

**Comment by nikkolasg** [comment]
@Daeinar thanks ! That's much shorter ;)
One more thing to ask:

1) **General**: do we need to keep our "own" namespace `dedis.epfl.ch/*subnamespace*/value` ?  This does not change the codebase.

2) The use of `UUID`everywhere. Does it make sense ? For example for `RoundID` which uniquely identify a round, it seems too much. We don't need to handle more than 2^32 or 2^64 different rounds at the same time do we ? With uuid, we can handle 2^128 rounds but it's still at the expense of one more 16 bytes comparison.

**Comment by ineiti** [comment]
Potential candidate for onet.v2
