### ISSUE TITLE
Add new repo for putting the SDA-libraries

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#425]
The new CrypTree (new name for SDA, propose others) should contain the following parts of cothority:
- cothority/lib/SDA and dependencies (lib/dbg, lib/crypto, lib/network)
- cothority/app/cothorityd as a library to be used in other apps
- Protocols: management, BFTCosi, JVSS

**Comment by nikkolasg** [comment]
I'm not sure about the Protocols part. SDA is only really only about the network overlay and being able to handle services and protocols. 
The actual use of JVSS, BFTCosi, management is only in cothority and therefore they're not needed by another repository (which then would make sense).

**Comment by ineiti** [comment]
where else should we put somewhat 'stable' protocols? It feels like a separate 'protocol'-repo is a bit overkill, no?

**Comment by nikkolasg** [comment]
That's where versioning comes into place. Having protocols / services at two places for me seems a bad idea (where should I get this protocol ? from cothority or sda ?). Everything (protocol or service) that is stable can be in cothority.vXX. Even if we consider cothority as experimental, if we use versioning, we should have stables protocols there otherwise it means our cothority is just full of non-stable garbish protocols ?

**Comment by mahdiz** [comment]
As a user of SDA (of course, the authors should vote here :)) , it would be great to have it completely independent from specific protocols such as Cothority, RoundHound, Byzcoin, etc. that seems to only *use* it.

This not only makes it less-confusing for developers who are unfamiliar with those protocols, but also makes deployment/updating of SDA easier (one would need to only get/see SDA changes when updating).

**Comment by nikkolasg** [comment]
@mahdiz thanks for contributing, it's always heartwarming to have user inputs :) (and BTW, I agree with you !)

On a side note, we have to forget about using standard protobuf encoding if we do that, since normally, when using protobuf, you should know in advance every messages that are to be used throughout the process. Decoupling SDA will necessarily make SDA completely independant of protocols/service messages. That's OK for me since from the beginning we never really aimed at something compatible with other languages, but mostly performance/bandwidth. But I'm guessing we will start at some point to care about this compatibility issue and we'll need to come up with a difference encoding scheme than protobuf (or maybe there's a way, I just don't see it know...)

**Comment by nikkolasg** [comment]
As discussed with @bford @ineiti @Liamsi @Daeinar  , it seems more reasonable for the moment to keep sda in cothority, but keep the option in mind if we need that separation later. 
However, I proposed that we move `cothority/lib/sda` to `cothority/sda` so sda gains a more central part of the repository. 
In fact, ideally, I'd like to move all the `lib/` folder to the top level namespace of cothority. I know having a `lib/` folder seems also a good idea, but looking at golang repositories, it does not seem to be the *idiomatic* golang organization: Most repo seems to have more top level packages rather than a lot of subpackages ("a-la-Java"). See [0] for most popular golang repo, and [1], [2], [3] are the first most popular repositories and they seems to use this idiomatic organization. Moreover, I find this organization much easier to grasp, rather than having to dig into many sub packages.
What do you think ?

[0] https://github.com/trending/go?since=monthly
[1] https://github.com/getlantern/lantern
[2] https://github.com/containous/traefik
[3] https://github.com/coreos/torus

**Comment by ineiti** [comment]
Sounds good. I propose we also add an issue about `cothority/lib/crypto` if it is not really used and only duplicates methods from `dedis/crypto`

**Comment by nikkolasg** [comment]
Yep. I guess we can maybe remove  `hashid,key,proof` but the rest seems used and not in dedis crypto. Schnorr signatures is only shown as an example IIRC but not as a library/module easy to use.

**Comment by nikkolasg** [comment]
This is done.
