### ISSUE TITLE
Move `monitor` to `simul`

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#490]
As cothority grows, the `simul` gets less important. So we should move the `monitor` to the `simul`-directory, as it is only used in there.

**Comment by nikkolasg** [comment]
mhhh  right. Sounds good. The only thing I'm worrying about is the `monitor.CounterIO` interface which is used in `network` and `sda`. Instead of putting `monitor.CounterIO` in the interface definition, we should maybe just embed the function directly 
```
type Connection interface {
 ... 
monitor.CounterIO
}
```
vs
```
type Connection interface {
 ... 
 Rx()
 Tx() 
}
```

**Comment by ineiti** [comment]
Or put the `CounterIO`-interface in `network`?

**Comment by nikkolasg** [comment]
I would not do that since that implicitly makes a dependency between the two packages (as it is now but it's bad!): `monitor` would need `network.CounterIO` which do not make much sense to me. 
If we just put the methods `Tx()` & `Rx()` in the interface that implements the `CounterIO` without `monitor` being imported & the two functions would still be helpful on its own.

**Comment by ineiti** [comment]
Done
