### ISSUE TITLE
Timeout on connections

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#523]
When a connection hasn't been used for a given time, close it, so it doesn't get stale. Related to #331

**Comment by nikkolasg** [comment]
What is our goal here ? 
From my point of view, it seems that we want to have only healthy active connections that we manage. 
I'm not sure timeout does not necessarily solve the problem because even before a timeout occurs, a connection can already be dead/dropped; and we can't put a timeout too short because then a healthy connection may be disconnected often while it should not.

 A heartbeat system for each connection may be a possibility. It would send kind of a `ping` at a fixed interval (10sec, 1mn) and check if it receives something in return. If not, then we drop the connection. If yes, then all is fine. A ping is a small message and any healthy connections between two hosts won't be dropped even if the hosts did not communicate actively during a certain time.

**Comment by nikkolasg** [comment]
Do we still want that for SDA refactoring ? Because this SDA Refactoring epic issue should be closed,it's been hanging for a while now.

**Comment by ineiti** [comment]
Done
