### ISSUE TITLE
Too extensive use of reflection

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#561]
Writing the timestamp server I re-discovered that we make extensive use of reflection. Not that I think that reflection is bad thing in general but it's still slower than alternatives and potential misuse (bugs) occur only during runtime instead of compile time. Hence, we should investigate if we could use less reflection. This isn't urgent at all (maybe even after `v1`) and would make our code a little faster and easier to use. One (non-critical) example of potential reflection overuse is `RegisterMessage` ([here](https://github.com/dedis/cothority/blob/b70b73dddb45abedd964629d6ed568523ecbcc2f/sda/processor.go#L142-L177)). If we expect a function of certain form as a parameter we should state that instead of `interface{}` and using reflection to make sure we actually got a function with certain amount of specific parameters and specific return types.

If you all agree it's worthwhile, I will write more specific what I mean (with some more examples) etc.

**Comment by nikkolasg** [comment]
I agree in the idea but  then for the example you give, I think the problem is that Go don't do implicit type casting of parameters of a function which is given in a parameter:
```
func MyFunction(incoming MsgType1) (MsgType2,error) {
....
}

// XXX This does not compile 
func RegisterFunction(fn func(incoming interface{}) (interface{},error) ) {
...
}
```
(See example https://play.golang.org/p/FBC60yEtzc)

The idea when starting to use reflection was the ease of use by PhD students. This assumption is the foundation of all (or most) of our code design here (using generic protobufs, generic registration of channel handlers etc). 
So again, I agree with you but at the same time, if we want to move away from reflection, then it won't be as easy for PhDs student as it is now (generic support is not part of Go). Is that a problem ? Is it really useful that PhD student must have generic protocol-agnostic framework ?   It's a discussion... 

For my point of view, when writing this comment, it seems to me we've picked the wrong language ;)

**Comment by Liamsi** [comment]
Now that you mention it, I remember I stumbled upon the `RegisterMessage` and trying to create a non-refection version of it and we even discussed this case some time ago. I'm still sure there is a way to change it in another way. And maybe there are more critical parts of the code (`RegisterMessage` isn't critical as it is only used at initialization). 
I don't really see how reflection makes the above example easier. A signature saying: "I'm expecting a function of the form `func(incoming Type1) (Type2,error)`" is easier ton understand as the current signature `interface{}` as the former is more explicit and the compiler would let you know if you used it wrong. But maybe there are other use-cases where reflection increases usability which I currently don't see.
But yes let's discuss this.

**Comment by Liamsi** [comment]
> For my point of view, when writing this comment, it seems to me we've picked the wrong language ;)

Let's change to Rust ;-)

**Comment by nikkolasg** [comment]
> I'm still sure there is a way to change it in another way.

Well, I did not dwell into the subject too much, but I did not find any naive approach that fulfills our goal:
* Being explicit and using the Golang type system
* Being generic so user can pass any struct, register anything.

I have some ideas, to make this EXTERNAL method not using reflection, but we'll have to use reflect more underneath, so it does not really solve anything. If you find one, I'd be happy to look at it! 

> I don't really see how reflection makes the above example easier

It's easier when users (PhDs) don't have to bend themself to use our library (having a struct that fullfills this exact set of methods even if they don't know what is it, etc), but it's more difficult for *us*. Here, PhDs just look at an example service, and mimick the same thing and they can already have a working protocol / service very quickly *because* they don't have to specify everything.

Again, I *agree with you*, in an ideal world, I would not even touch the reflect package and I would have one binary per application completely separated etc. But that means, we can't use the generic protobuf, we can't register any kind of message, so PhDs have to make their own versions etc etc. To my point of view, we use reflect to mimic genericity, and while that's not completely *bad*, that's not the best thing to do also, but at least it provides a *generic* framework to PhDs...

> Let's change to Rust ;-)

Definitely, at least you would be able to do these kinds of stuff in Rust easily, but then .. the Rust compiler is not easy :D

**Comment by Liamsi** [comment]
(See example https://play.golang.org/p/FBC60yEtzc) 

I think the idiomatic golang-version would be to use interfaces (not `interface{}`) Quickly hacked your example to compile without using reflection, but yet it's generic (the methods can take anything, which fullfills the interface). 
https://play.golang.org/p/gqYb5PtBNn
Not sure if in our case we could come up with a common interface for all use cases (probaly not)

**Comment by nikkolasg** [comment]
I see, but in your example, it's generic *up until the getRelevantData* method, which returns an *`int`*. So imagine we change the return type to bytes (so we can embed the data into a `ClientRequest` which is what `RegisterMessage` is used for). That means that every user have to make their `GetRelevantData` for each packet they use, and in each of these methods they will repeat the `network.MarshalRegisterType(...)`. 

It seems to me, we will always find a wall between:
*  being generic to allow anything + not having to make repetitive calls
* using the type system
In Golang at least.

Your idea works, but then it puts more work for the PhD students, there's always a tradeoff, there's no magic solution. For me, it brings back to the same discussion: do we  want/need to help  PhD in way they have basically nothing to do except coding the logic ? How far do we need to help them ?
For the moment, they're quite happy about our framework because we made *all* the hard work and the repetitive calls for them.

**Comment by Liamsi** [comment]
> I see, but in your example, it's generic up until the getRelevantData method, which returns an int. 

Trying to resist and wait for the reply but ... OK, if we really, really can't find a common behaviour among the objects here we have to use an `interface{}`. I agree on that. But still I wouldn't check *everything* with reflection. Only what we can't know about upfront. Obviously we know that we expect a `func` for instance and not an `interface{}` in `RegisterMessage`. Coming back to the `int` return type, this would mean: https://play.golang.org/p/Lu-N72dAtI (I see this example as it is doesn't make much sense anymore, but for `RegisterMessage` it would)

**Comment by nikkolasg** [comment]
I know we just discussed that but it's best to put it in writing:
Now we just had our `RegisterMessage` a bit more cleaner by specifying it expects a function, but we've just put more load to the PhD student who now must implement this `getRelevantData` for each packet it uses. Most of the time it will be something like:
```
type MyStruct struct {
...
}

func (ms *MyStruct) GetRelevantData() interface{} {
return ms
}
```
I'm not sure it makes more sense from the PhD perspective to have to define all of these "identity"  (algrebraic sense) functions by himself. On the other hand, now we don't have to use reflection for this function, so we're more happy (so we're more productive etc etc :D)

**Comment by bford** [comment]
Sorry to jump in now, given that I haven't really managed to stay in the loop on these discussions...  But taking a look at the code, I tend to agree with Ismail that reflection may be getting over-used a bit here.  

Especially the long list of manual checks within RegisterMessage() to verify that parameter f is "flexible" but has a certain very specific form, immediately suggests to me that this code is "working too hard" on behalf of the caller.  In situations like these, if the caller has an 'f' with a slightly different (e.g., more purpose-specific) type signature and needs an 'f' that it can pass here, Go makes it pretty trivial for the caller just to create a suitable wrapper-function to adapt the type signature (it has higher-order functions after all!) and pass that as the 'f' parameter.

But another, perhaps more serious concern I have with the way RegisterMessage appears to work is that it's starting to embed some seemingly very Go-language-specific things in the actual wire protocol: in particular, the "PacketUUIDs" computed from Go type IDs via network.RTypeToPacketTypeID.  This kind of thing sounds like a recipe for trouble and complexity the first time code in any other language wants to implement an interoperable protocol, or something like that.  Avoiding this kind of language-dependence is one of the main reasons we're using protobufs instead of gob format, for example.

In general, I feel like the SDA API's design might be trying to overuse "language-level generic interfaces" for these types of purposes - with the results of (a) accidentally making the wire-protocol overly language-dependent, and (b) running smack into Go's language-level type-system limitations.

In particular, could many of these interfaces perhaps be defined to deal with messages not as unmarshaled language-level objects generically represented via interface{}, but instead as generic *marshaled* objects passed in interfaces as simple byte-slices?  Why not let the client (e.g., a particular service) decide which specific encoding to use for particular types of messages, and similarly let the client worry about distinguishing and demultiplexing different types of messages?  That way, the client (e.g., service) can simply define its own local message-ID space that can distinguish among the messages it's expecting to process, and only those.  No need for UUIDs because they don't need to be globally unique anymore, only unique within a given service or other relevant context.  

Or to whatever extent a "truly global" ID is needed (e.g., for disambiguation between different services), that should be based on explicitly-specified strings of some kind (which might or might not happen to be UUIDs), not automatically-generated in a language-dependent fashion.

**Comment by bford** [comment]
Oh, and no need to coddle PhD students *that* much.  Any PhD student in our group should be able to write a wrapper-function or to invoke marshal/unmarshal functions for themselves! ;)

**Comment by ineiti** [comment]
Part of that code came into life after having written the 100th iteration of `MarshalBinary` and `UnmarshalBinary` for a structure. Since then I liked being able to do `MarshalRegisteredMessage` and just relax, instead of writing 10 times a `simply define its own local message-ID space` ;)

With regard to interoperability, I don't think we need to care that much with regard to messages passed inside of protocols. Only the service-API needs to be interoperable, this is why we want to have some json-handling there. This is part of what I'm doing with the student who is developing the Android-application. See #475 on that.

**Comment by Liamsi** [comment]
Thanks for your input Bryan!

@ineiti any thoughts on the reflection issue in general? I don't think it brings much convenience here and in other places. Some of it might be a matter of taste (I prefer a clear method signature instead of sth telling you, you can put anything `interface{}` here). But with regard to performance and (compile-time) code correction, do you think we should try to slightly cut on reflection? 
There are seemingly many other places like the first example (see [`GetReply`](https://github.com/dedis/cothority/blob/master/sda/processor.go#L245-L274) for example)

**Comment by bford** [comment]
By the way, it should not be necessary to have a whole bunch of calls to MarshalBinary/UnmarshalBinary in a given module, even if there are many message types to be marshaled/unmarshaled.  With Protobuf, my understanding of the standard way to handle "union/variant/case-switch" types is simply to embed them as (optional) members of a struct representing a "meta-message".  For example, taking services/medco as an example, if you have:

type SurveyCreationQuery struct { ...
type SurveyResponseQuery struct { ...
type SurveyResultsQuery struct { ...
type ServiceResponse struct { ...
type SurveyResultResponse struct { ...

What you then do to create a generic "message" that can multiplex/demultiplex to/from *all* of those is just define:

type SurveyMessage struct {
  CreationQ *SurveyCreationQuery
  ResponseQ *SurveyResponsequery
  ResultsQ *SurveyResultsQuery
  ...
}

Then, you just marshal/unmarshal SurveyMessage, and in contexts in which only one of those actual messages is expected, you enforce the invariant that only one of the members of SurveyMessage is non-null.  And the struct-field-IDs that Protobuf automatically assigns sequentially to the members of SurveyMessage implicitly act as the locally-unique (and very efficient) message-IDs for multiplexing and demultiplexing.

If there are contexts in which it might make sense to pass not just one message but a batch of messages together, it might be even better to define SurveyMessage as:

type SurveyMessage struct {
  CreationQ []SurveyCreationQuery
  ResponseQ []SurveyResponsequery
  ResultsQ []SurveyResultsQuery
  ...
}

Then, in single-message contexts, the invariant is that exactly one field in a given SurveyMessage is size-1 and all the others are size-0 - but in contexts where a batch of (same or different-type) messages could sensibly be processed at once, then it's trivial to allow any number of the sub-fields to have any number of instances of a given message sub-type.

**Comment by nikkolasg** [comment]
> In general, I feel like the SDA API's design might be trying to overuse "language-level generic interfaces" for these types of purposes - with the results of (a) accidentally making the wire-protocol overly language-dependent,

The `PacketTypeID` is just an alias to `uuid.UUID` which is a `[16]byte`. Each packet have their own unique id and it's fixed (according to the name). So it's something that can be put in a RFC or so:
```
SDAMessageID = 0xffff...f1ad128ec
TreeMessageID = 0x2fe198a4r....
...
```
It's not that much different that using a fixed `CellType` id like in Tor where each type of message has its own identifier (which is more like an 32-bit integer I think but I don't recall exactly). 
In short, I don't see any language-dependency problem here. What did you mean ?

> and (b) running smack into Go's language-level type-system limitations.

We run into **because** we *coddle* PhDs... Usually, it seems that in any network-related Golang projects, you define **clearly all the messages type that you expect to receive and send**, generate your protofiles / bson / json definitions, and work from there. Here, we allow students to simply dynamically register messages so it's not fixed **at all**. 
* One one hand for the moment we had good feedback on this design because 
  + it's really easy to understand & fast to code: "code only the logic", the rest is done. The rest includes all the networking management, the overlay management, the encoding etc... We've been writing protocols quite fast with this design.
  + like @ineiti said, no need to Marshal / Unmarshal your message everywhere (and it's done **a lot**).
  
* On the other hand, it's not interoperable *at all* for all the *inter-cothority* messages. But using IDs is not the main problem if we want interoperability, the main problem is that we define structs inside other structs (to allow all the benefits described above). So our protobuf files definitions looks like a lot of packets each one containing many "bytes" fields... which does not help much ;)
See below: 
```
network.NetworkPacket :

message NetworkPacket {
  required bytes msg_type = 1;
  required bytes msg = 2;
}

sda.NetworkProtocolMsg :

message NetworkProtocolMsg {
  optional Token from = 1;
  optional Token to = 2;
  required bytes msg_type = 3;
  required bytes msg_slice = 4;
}

```


Like @ineiti said, for external operations, we plan to have a REST API which can be easily integrated in many other languages.

**Comment by bford** [comment]
Also, lest I seem to be siding too much with Ismail, I don't really agree that "just switch to Rust" is a solution here. :)  Even though Rust is great and I want to do stuff with it, my experience from C++/Haskell/etc is that whenever you really start trying to push the generic-typing capabilities of fancy type systems like these, you quickly run into all sorts of trouble.  Maybe Rust will be the exception to this rule, but I doubt it. ;)

**Comment by Liamsi** [comment]
> Also, lest I seem to be siding too much with Ismail, I don't really agree that "just switch to Rust" is a solution here. :) 

Moving to Rust right now was more of a joke than anything else.  We are much faster in golang and it has everything we need. But if we want to stay with all this reflection and checking types and structure during runtime, we would better move to ruby or something that has some kind of "Duck-typing" (also not serious) ;-)

**Comment by nikkolasg** [comment]
This issue is related to the #287 issue.
