### ISSUE TITLE
Network - Routers connecting at the same time

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#577]
In our implementation, if two Routers connect to each other *at the same time*, at the end there will be 2 connections between each other. Indeed, when r1 wants to connect to r2, it will call `connect()` which will start an `identityExchange`  and **then** r1 registers the connection. Since r2 wants to send at the same time, r2 does still not have the previous connection, so it do the same: call `connect` & start `identityExchange` etc. And now we have two connections instead of one.

The problem here is that we register a connection AFTER `identityExchange`. One obvious solution would be to register the connection BEFORE and then add a field / map saying ` connection's handshake in progress` or `connection's handshake done` so the Router knows if it has to connect, or to wait that the handshake finishes.

In the PRs #574 I just append into an array all the connections registered under the same `ServerIdentityID` & I iterate over this array when calling `Close`.

**Comment by bford** [comment]
Assuming I correctly understand the problem (being not thoroughly familiar with this part of the code), you're trying to avoid opening two separate TCP connections between a given pair of peers A and B, one A->B and the other B->A, when in principle you only need one?

I certainly agree with having the optimization of trying "at least a little" to reuse connections in both directions if readily feasible: e.g., if A contacts B and then sometime later B wants to initiate requests to A, then B should be able to find out about and reuse the A->B connection.  This is standard practice for P2P overlays.  However, let's be careful not to "try too hard" to avoid ever ending up with duplicate connections, as they can easily happen in all sorts of race conditions (A wants to connect to B at "about the same time" as B wants to connect to A), and trying too hard to avoid duplicate TCP connections in such situations can easily lead to much worse complexity and race conditions.  In other words, the code should always at least be tolerant of having multiple (potentially redundant) connections between a given pair of nodes, even if it tries to avoid that happening all the time.

In particular, there are a lot of bad things and complex side-effects that can easily happen if you the overlay logic tries to do stuff like "open an outgoing connection, but then notice that an incoming connection from the same peer came in in the meantime, so close the outgoing connection we opened..."  (But oops, the other side received that outgoing connection and was starting to try to use it, and because of this the other side simultaneously closed the connection it had opened to us, and now we have no working connections...)  Just saying this area of complexity is a trap I've fallen into before; try to avoid it and keep it simple. :)

**Comment by nikkolasg** [comment]
> Just saying this area of complexity is a trap I've fallen into before; try to avoid it and keep it simple. :)

Hehe, thanks for sharing the experience. The current solution was the simplest for me at the time: just having an array of connections referenced by the identity (public key) of the server we are communicating with. So if two connections are opened simultaenously, then there will be two connections registered. Only the first one in the array will be used, but at least we're sure we close the two when calling `Close()`. This last point is important because in our tests, we always check if there are any *leaked* go routines at the end of each tests. (An opened connection will read in a for-loop in a goroutine)

**Comment by ineiti** [comment]
OK, if it's too complicated to make it nice, leave as is.
