### ISSUE TITLE
network testing

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#633]
Replace `t.Fatal` with `log.ErrFatal` so that an eventual error in a _go_-routine will be caught.

What to do with things like

https://github.com/dedis/cothority/blob/master/network/router.go#L66

that have to be caught but if tested produce output? Ignore (even though I like a clean output) or make `Router.Start` return an `error` that we can test?

Same with `ServerIdentityToml.ServerIdentity` - keep `log.Error`, but when we test the error, we will have something on the output?

Or redirect the `log.stdErr` and check that it's filled?

**Comment by nikkolasg** [comment]
Yeah I also thought about this issue. Taking your example of the router, to me, what matters most is that the connection is not made and is closed if the sending of the server identity is not made correctly. In that sense, I'm not necessarily a fan for the moment of having an explicit error mechanism (return or callback) here *only* for the purpose of testing. 
It would make sense later if we would implement an anti-DDoS/rate-limiting mechanism for example.

On the other hand, it would be nice if our tests which generate error outputs are *only* generating the ones we want (and not some random error output). So a "correct-behavior" test should not output any error at all and a "wrong-behavior" test should output some error and **indeed** we should make sure it appears. 
As you start to know me, I'm growing fond on the way Tor people are coding and they kind of  had the same problem a while ago ( see [maling list](https://www.mail-archive.com/tor-dev@lists.torproject.org/msg08745.html) ). The way they check if an error occurred is indeed checking the log. Their log system is a bit more complex than ours it seems since it uses a linked list but basically they have a mock logging framework for unit tests and they can check if a specific message appeared inside ( relevant [source code](https://github.com/torproject/tor/blob/master/src/test/log_test_helpers.c#L126).

What do you think ?

**Comment by ineiti** [comment]
The `log`-library now has a way to save all log-output and search in it.
