### ISSUE TITLE
Check return-value of protocol-handlers

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#686]
Protocol-handlers should return an error, which is checked in issue #631.

**Comment by nikkolasg** [comment]
I'm copy/pasting my comment from the PR since it make most sense to discuss the issue in itself here:
I'm not necessarily sure it's a good idea to make SDA handles everything of the protocol, especially errors. It's way more easy to debug a protocol which log itself the error than the SDA reporting an out-of-context error like : `sda.TreeNodeInstance.DispatchHandler:256 Error from protocol: XXX XXX`. I don't any good logical reasons regarding the API, the semantic or even the implementation (it adds a constraint on the function that must be given and the checks resulting out of it).

Regarding the code, it's exactly the same amount of code:
```
if err != nil {
   return err
}
```
vs 
```
if err != nil {
    log.Error("ProtocolBLABLA: ",err)
}
```

**Comment by ineiti** [comment]
It's not the same: your second code-snippet misses a `return` ;)

Anyway, if you don't want handlers to return an error, then we should open an issue `removing error return from handlers`. As-is now, handlers can return errors which are silently ignored. As I trapped more than once over these, I prefer that we either merge these PRs, or make an issue that no handler can return an error.

But for the moment quite a lot of handler-methods return errors, so either we rewrite all these methods, or we merge this PR.

**Comment by nikkolasg** [comment]
> It's not the same: your second code-snippet misses a return 

Well there's no need for a return if it does not return something !

Mhhhh Ok i see, just looking at the PR I thought handlers were not returning any errors, but you're right they are currently, so I agree with you that these should be handled then.

+1

**Comment by ineiti** [comment]
If there's an error, you usually quit the function without continuing, even if there is nothing to return, no?
