### ISSUE TITLE
Make simulations independant

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#717]
Now: protocols and services that need simulation need to be in the cothority-repo
Desired: other repos can import cothority and use the simulation
Pro: this could open the way to separate cothority and the protocols/services in two repos.

**Comment by nikkolasg** [comment]
> Now: protocols and services that need simulation need to be in the cothority-repo

Well, yes and no. That's why forks exists, so you can have your own code in your own repo and still launch simulations. I've talked with @lbarman about this possibility also so they do their own fork. 

> Pro: this could open the way to separate cothority and the protocols/services in two repos.

Even if it's not for now, I'm already not a super fan of this solution. We already tried to decouple the protocols/services with CoSi and it was really a nightmare to maintain... but hey who knows ? maybe we did it wrong! We could have tried the `vendor/` folder where we put the code of the imports at a specific version already....

Anyway, I'm more for well-decoupled *packages* but have a big monolithic repository where everything is consistent. See [[1](https://danluu.com/monorepo/) and plenty of others if you search on Google.

**Comment by ineiti** [comment]
Done
