### ISSUE TITLE
CoSi-signing improvement

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#799]
As we don't have yet a good exception-mechanism, we could add at least a simple test of which servers are up and then use that to sign. So:

1. verify running servers using `check.Servers` from cothority/cosi
2. run the signature using those servers
3. write the public keys of the servers to the signature file

**Comment by nikkolasg** [comment]
I like the idea of having something that can work without all servers being present !!

However, I would prefer to start using our "bitmask" approach that we have implemented in `crypto/cosi` instead of giving the public keys into the signature file, which removes the trust you might have in your pre-defined keys stored somewhere...

For example, since we are **not** talking about any exception *inside* the `Tree` (overlay), I guess we could do your step 1), and then depending on that, give the `CoSi` protocol 
 + the list of available servers, in the `TreeNodeInstance` as *usual*
 + the complete list of servers that are supposed to participate

Then the protocol can apply the bitmask technique on the signature with those two informations.
That way, any signature produced is still valid from the verifier point of view.

**Comment by jeffallen** [comment]
This will be fixed when we integrate Raphael Dunant's code.
