### ISSUE TITLE
remove uses of SendRaw

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#998]
Replace them with proper Protocol calls.

example: skipchain.go has SendRaw(node, &GetBlock{unknown}), which should be using ProtocolGetBlocks instead.

There are lots and lots of them in pop/service as well.

**Comment by kc1212** [comment]
SendRaw is useful when you want to send a single message to one specific node. Doing this from scratch in a protocol is a bit cumbersome. Maybe we can create a helper function that returns a protocol that achieves this functionality.

**Comment by nikkolasg** [comment]
The reason this methods exists, as @kc1212 said, is to said a message directly to another node, controlling what's going into the network. No magic autmatic marshalling, no magic handling by whatever middlelayer in onet (interoperability, possibility of a clear spec, etc)
Hence, (to me) the reason it really exists : it makes it clearer what's happening in the code base, and as such it impacts the "cuddling" of the students because it's "harder" to quickly prototype something. It's one of the point related to the big debate: "interoperability / production code" vs "completely generic library which can do a lot of stuff magicly (i.e. using reflect)".

**Comment by jeffallen** [comment]
So it needs to exist. Closing.
